set -x
BUILD_TYPE=${BUILD_TYPE:-Relese}
BUILD_DIR=${BUILD_DIR:-./build}
mkdir -p $BUILD_DIR/$BUILD_TYPE/bin $BUILD_DIR/$BUILD_TYPE/lib
ln -sf $BUILD_DIR/$BUILD_TYPE/compile_commands.json
cd $BUILD_DIR/$BUILD_TYPE
cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ../..
make 